apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-java-web-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tanzu-java-web-app
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      #url: https://github.com/sample-accelerators/tanzu-java-web-app
      #https://github.com/PengliuIBM/tanzu-java-web-app-1
      url: http://github.com/PengliuIBM/test-tap-web
      ref:
        branch: main
